apiVersion: 1

datasources:
  - name: clickhouse-direct
    uid: clickhouse-direct
    type: vertamedia-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    basicAuth: true
    secureJsonData:
      basicAuthPassword: ""
    basicAuthUser: "default"
    editable: true
    jsonData:
      addCorsHeader: true
      usePOST: true
      useCompression: true
      compressionType: gzip
